name: Test
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ["", "defmt", "custom-error-messages", "defmt,custom-error-messages"]
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri rust-src
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools
      - run: cargo +stable install cargo-llvm-cov

      - run: cargo +stable build --no-default-features --features "${{ matrix.features }}"
        env:
          RUSTFLAGS: "-D warnings"
      - run: cargo +stable test --no-default-features --features "${{ matrix.features }}"
        env:
          RUSTFLAGS: "-D warnings"
      - run: cargo +nightly miri test --no-default-features --features "${{ matrix.features }}"
      - run: cargo +stable llvm-cov --no-default-features --features "${{ matrix.features }}"
      - run: cargo +stable build --examples --no-default-features --features "${{ matrix.features }}"
        env:
          RUSTFLAGS: "-D warnings"
      - run: cargo +stable doc --no-default-features --features "${{ matrix.features }}"
        env:
          RUSTFLAGS: "-D warnings"
          RUSTDOCFLAGS: "-D warnings"
